# Thông tin k?t n?i SQL Server (C?ng m?c ??nh là 1433)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=medical_care;encrypt=true;trustServerCertificate=true;

# Tài kho?n ??ng nh?p SQL Server
spring.datasource.username=sa
spring.datasource.password=123456

# C?u hình Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

